# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Tu2525.OpenCrosshair
PackageVersion: 0.5.4
InstallerType: exe
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/Tu2525/OpenCrosshair/releases/download/v0.5.4/OpenCrosshair-Setup.exe
    InstallerSha256: 7125AB1E86B94663B3C2612A16E19972FCA4534342AA41D70C2FFF8D04190E1F
AppsAndFeaturesEntries:
  - DisplayName: OpenCrosshair
    Publisher: OpenCrosshair
    DisplayVersion: 0.5.4
ManifestType: installer
ManifestVersion: 1.12.0
